name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.0.0

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Check types
        run: deno task check

      - name: Run tests
        run: deno test -A --no-check --coverage
        # run: deno test -A --no-check --coverage

      # - name: Generate coverage
      #   run: deno coverage --lcov coverage/ > cov.lcov

      # - name: Upload coverage to Coveralls.io
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
      #     path-to-lcov: cov.lcov

  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.0.0

      - name: Check types in doc
        run: deno task check --doc

      # TODO enable once the plugin is published and all examples are functional
      # - name: Run tests in doc
# run: deno task test --no-check --coverage --doc
